### ISSUE TITLE
Questions & Comments on differences between Pipe and Flow

### ISSUE THREAD

**Issue by a-lipson** [IBM/fp-go#29]
https://github.com/IBM/fp-go/blob/45e05f25ff75421a4479a525ae0cbabd9869eae2/function/gen.go#L27-L40

I have been following [this guide](https://rlee.dev/practical-guide-to-fp-ts-part-1) to fp-ts which you linked to in [your article on the IO Monad in Go](https://medium.com/better-programming/investigating-the-i-o-monad-in-go-3c0fabbb4b3d#:~:text=in-,Ryan%E2%80%99s%20blog,-.%20In%20this%20context) 
I am reading the part about the difference between pipes and flows.

The author, Ryan, notes that the difference in the function signature between pipes and flows is that one operates on a value as the initial term while the other operates on a function.
```
pipes: A -> (A->B) -> (B->C) -> (C->D)
flows: (A->B) -> (B->C) -> (C->D) -> (D->E)
```

Can we abstract values to be a function that goes from no value to A?
Borrowing the Unit type from Haskell, `()->A`
This satisfies the function signature of the flow composition in that the Unit to A function `()->A`, matches the `A->B` type as the initial value of the flow.

I suppose that this would just lead to excessive syntax in go. 
Unlike in Haskell, where `let x = 42` as a value is syntactically more verbose than its function counterpart `x = 42` which takes no inputs.
```go
// define a value
x := 42

Pipe(x, f1, f2, ...)

// define a function that takes Unit and returns a value
f := func() int { return 42 } 

Flow(f, f1, f2, ...)
```

In addition, in terms of usage, it seems like creating a flow is a composition tool which allows one to build more complex functions from simple ones, whereas pipe is used for the actual evaluation. So, I can see the difference in use case between the two functions.

However, from the standpoint of reducing complexity, given that we cannot overload nor are we being able to use variadics for `n` input functions, reducing the PipeN or FlowN would be ideal.

I suppose one could write,
```go
input := 42 
output := FlowN(f1, f2, ...)(input)
```
But that breaks left-to-right readability where we can have
```go
input := 42
output := PipeN(input, f1, f2, ...)
```

~~A different question I have, relating to generics, is the importance of the type parameter order
for example, in this function signature, there are two functions with two output types. These output types are set at the end to be any. 
Is there a particular reason for defining the function signature types first and then the other (value?) types?~~
https://github.com/IBM/fp-go/blob/45e05f25ff75421a4479a525ae0cbabd9869eae2/function/gen.go#L87-L93
~~for example,~~
```go
func Flow2[T0, T1, T2 any, F1 ~func(T0) T1, F2 ~func(T1) T2](f1 F1, f2 F2) func(T0) T2
```
~~My guess would be that either, a) it's good convention to leave the plainly `any` types at the end of the type parameter bit, or b) F comes before T in the alphabet.
I haven't done much work with go generics in the past, so I am unfamiliar with the convention. I think that both ways of defining the signature are legible, but, again, I was wondering if there was a particular reason.~~

answered the above with another look at the readme.

Lastly, I look hope that generics for methods in go will one day be added so that we can introduce `bind` and not have to worry about `Pipe100`!

**Comment by a-lipson** [comment]
Thank you very much for your explanation!

**Comment by CarstenLeue** [comment]
@a-lipson after pondering about this a bit more, maybe the `Lazy` monad is a better fit to answer your question because it fits into the normal use of `Pipe` and `Flow`. Example:

```go
import (
	"strconv"

	L "github.com/IBM/fp-go/lazy"
)

func ExampleLazy_creation() {
	// lazy function of a constant value
	val := L.Of(42)
	// create other nullary (lazy) functions via Pipe or Flow
	valS := F.Pipe1(
		val,
		L.Map(strconv.Itoa),
	)

	fmt.Println(valS())
}
```

**Comment by a-lipson** [comment]
I'll take a closer look at the lazy monad!
