### ISSUE TITLE
Would a function family like `BindNofVariadic()` be useful? | Chaining w/ inheritance

### ISSUE THREAD

**Issue by a-lipson** [IBM/fp-go#38]
Please forgive me for creating this issue for creating this issue if this functionality is already possible with a composition of extant functions.

Nonetheless, let me describe the scenario I am working with.

I have a function from a library that takes a single variadic input. I have a pipeline of functions that eventually needs to put an item into this variadic function. 

The current approach that I am taking is to pipe up to the last function and store that output, then to pass the output to the the library's function.

I have also taken a look at using the `Unvariadic0` function, but I think the method above is simpler.

This leads me to wonder if functions that would take functions with variadic arguments and produce functions with a finite set of arguments would be helpful.

While looking for a way to accomplish this, I found the bind and ignore functions which are similar, but I don't fully understand them. Hence why I imagined that there probably exists a way to accomplish what I was trying to accomplish, yet I cannot see it.

I might implement the `BindNofVariadic` function like this,

```go
func Bind1ofVariadic[T, R any](f func(...T) R) func(T) R {
    return func(t T) R {
        return f(t)
    }
}
```

Then for two arguments,

```go
func Bind2ofVariadic[T, R any](f func(...T1) R) func(T, T) R {
    return func(t1, t2 T) R {
        return f(t1, t2)
    }
}
```

One potential consideration would be the case where a function has its variadic argument in the second, third, fourth, etc. position. As is the case with the `UnvariadicN` family of functions.

The minimal differences between `Bind1...`, `Bind2...` and `BindN...` suggest to me now that this functionality might be accomplished by some form of `UnvariadicN` and then some sort of indexing of the resulting slice.
For example, if there were a family of slice builder functions from some data, like `FromN`, then one could go from the single value to a `From1` to a `Unvariadic0` on some function `f`. However, I think this might be just another version of the same proposed solution.

Or perhaps this problem is indicative of some inherent design issue, rather than reason for a new function.

---

Another question that I have is about how chaining with inherited types works.

Here are two examples that I created to try to better understand.

```go
type MyString string

// need to define a cast method
func (m MyString) String() string { return string(m) }

func TestCastingInPipeline() {

	var text MyString = "hi"

	uppercase := strings.ToUpper
	cast := MyString.String

	out1 := F.Pipe2(text, cast, uppercase)

	out2a := uppercase(cast(text))
	out2b := uppercase(string(text)) // works without cast method

	// assert.Equal(t, out1, out2a, out2b)
}
```

and

```go
type Thing interface {
	Do() int
}

type MyType struct{}

// make MyType implement Thing
func (m MyType) Do() int { return 1 }

func ThingAction(thing Thing) int { return thing.Do() }

func TestInheritancePipeline() {

	example := MyType{}

	// MyType implements Thing but type of MyType != type of Thing
	out1 := F.Pipe1(example, ThingAction)

	// MyType implements Thing
	out2 := ThingAction(example)

	// assert.Equal(t, out1, out2)

}
```

Aside from this, I am enjoying trying to implement functional design patterns in my go project.
I am following the tutorials that you have linked (both Ryan Lee's blog and Professor Frisby's Mostly Adequate Guide to Functional Programming)
In addition, I am trying to learn Haskell and Category Theory (mainly following Bartosz Milewski's lectures on YouTube at the moment) to have a better understanding of the functional concepts before employing them in go.

Thank you very much for this resource and assistance!

**Comment by CarstenLeue** [comment]
On variadic function support. So far this is the train of thoughts:

- variadic arguments are always the last arguments in a function signature. So the set of `UnvariadicN` methods takes a function with `N` non-variadic arguments and adds a `N+1st` that represents the array(slice) of the variadic arguments 
- the set of `BindNofM` functions is meant to reduce the arity of a `M`ary function by pinning down (binding) the some of the parameters to static values
- the composition functions `PipeN` and `FlowN` work on unary functions, i.e. one input one output
- if you want to use a function taking more than one parameter in a composition, then the idea is to wrap the parameters into a single "wrapper" and pass that wrapper as a single argument.
  - if all parameters are of the same type you can use an array and `A.From`
  - if the parameters are of different types, use a tutple and `T.MakeTupleN` and `TupledN/UntupledN`
  
A simple usecase using `Unvariadic0` would be

```go
func fromLibrary(data ...string) string {
	return strings.Join(data, "-")
}

func TestUnvariadic(t *testing.T) {

	res := Pipe1(
		[]string{"A", "B"},
		Unvariadic0(fromLibrary),
	)

	assert.Equal(t, "A-B", res)
}
```

From a naming perspective the naming `func Bind1ofVariadic[T, R any](f func(...T) R) func(T) R {` does not really fit the naming of the existing `Bind` functions, since for the existing ones the set of numbers after `Bind` identities the indexes of the parameters to pin down. In `Bind1ofVariadic` the `1` is rather the arity of the resulting function.

**Comment by CarstenLeue** [comment]
How about this:

- we add a function similar to `UntupledN` but for slices, e.g. 

```go
func Unsliced2[F ~func([]T) R, T, R any](f F) func(T, T) R {
	return func(t1 T, t2 T) R {
		return f([]T{t1, t2})
	}
}

```

and then we can use this in conjunction with `Unvariadic0` like so:

```go
func fromLibrary(data ...string) string {
	return strings.Join(data, "-")
}

func Unsliced2[F ~func([]T) R, T, R any](f F) func(T, T) R {
	return func(t1 T, t2 T) R {
		return f([]T{t1, t2})
	}
}

func TestVariadicArity(t *testing.T) {

	f := Unsliced2(Unvariadic0(fromLibrary))

	res := f("A", "B")
	assert.Equal(t, "A-B", res)
}

```

**Comment by a-lipson** [comment]
Hi @CarstenLeue, thank you very much for your explanations. 

I did not realize that the inheritance problem that I was encountering was the same as the variant/covariant data types. I am still learning.

I think I have a better understanding of the problem now, and I can certainly see how it's perhaps not possible to do a convertibility check and the only workaround appears to be some sort of specific casting method or a loss of type-safety.

I would prefer a boilerplate casting method as opposed to a loss of type safety.

---

With regards to the variadics, as of my current understanding, it seems that `UnslicedN` would be a helpful series of functions. 
However, I think that I need to learn more about currying and composition of curried functions in order to find different approaches to the same issue. So, I would defer to your much much more experienced opinion if such a function family would be both useful, but, more importantly I'd imagine, conducive to writing good code.

Additionally, I will try testing composition of functions with multiple input parameters using the tuple functions. 

Once again, thank you!
