### ISSUE TITLE
ReaderIO / ReaderIOEither dependency injection sample

### ISSUE THREAD

**Issue by darky** [IBM/fp-go#99]
Would be nice to have sample for `ReaderIO` / `ReaderIOEither` with _Dependency injection_
It's very useful in _Unit testing_ to use `Reader` for passing mocked _IO_

**Comment by CarstenLeue** [comment]
Hi @darky I have converted gcanti's [example on reader dependency](https://dev.to/gcanti/getting-started-with-fp-ts-reader-1ie5) injection to fp-go: https://github.com/IBM/fp-go/tree/main/samples/getting-started-with-fp-ts/reader

For the I/O related usecase I have added:

https://github.com/IBM/fp-go/tree/main/samples/readerioeither/example1

Is this what you had been looking for?

**Comment by darky** [comment]
Hi @CarstenLeue 
Great! Thanks!
